# enable zmk studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# firmware pointer control (&mmv / &msc / &mkp on the mouse layer)
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y